### ISSUE TITLE
class GFRemove does not have a method "display_changelog"

### ISSUE THREAD

**Issue by Bad-and-Mad** [bhays/gravity-forms-remove-entries#4]
```
PHP Fatal error:  Uncaught TypeError: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class GFRemove does not have a method "display_changelog" in /wp-includes/class-wp-hook.php:308
Stack trace:
#0 /wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters()
#1 /wp-includes/plugin.php(517): WP_Hook->do_action()
#2 /wp-admin/plugin-install.php(82): do_action()
#3 {main}
  thrown in /wp-includes/class-wp-hook.php on line 308
```

**Comment by flexcodenet** [comment]
Same here.

**Comment by Gsiete** [comment]
I manually commented out the line 56:
// add_action('install_plugins_pre_plugin-information', array('GFRemove', 'display_changelog'));
